// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package models

import (
	"time"
)

type HrDepartment struct {
	DeptID           int32          `db:"dept_id" json:"deptId"`
	DeptName         string `db:"dept_name" json:"deptName"`
	DeptModifiedDate time.Time   `db:"dept_modified_date" json:"deptModifiedDate"`
}

type HrEmployee struct {
	EmpEntityID       int32          `db:"emp_entity_id" json:"empEntityId"`
	EmpEmpNumber      string `db:"emp_emp_number" json:"empEmpNumber"`
	EmpNationalID     string `db:"emp_national_id" json:"empNationalId"`
	EmpBirthDate      time.Time   `db:"emp_birth_date" json:"empBirthDate"`
	EmpMaritalStatus  string `db:"emp_marital_status" json:"empMaritalStatus"`
	EmpGender         string `db:"emp_gender" json:"empGender"`
	EmpHireDate       time.Time   `db:"emp_hire_date" json:"empHireDate"`
	EmpSalariedFlag   string `db:"emp_salaried_flag" json:"empSalariedFlag"`
	EmpVacationHours  int16  `db:"emp_vacation_hours" json:"empVacationHours"`
	EmpSickleaveHours int16  `db:"emp_sickleave_hours" json:"empSickleaveHours"`
	EmpCurrentFlag    int16  `db:"emp_current_flag" json:"empCurrentFlag"`
	EmpModifiedDate   time.Time   `db:"emp_modified_date" json:"empModifiedDate"`
	EmpType           string `db:"emp_type" json:"empType"`
	EmpJoroID         int32  `db:"emp_joro_id" json:"empJoroId"`
	EmpEmpEntityID    int32  `db:"emp_emp_entity_id" json:"empEmpEntityId"`
}

type HrEmployeeClientContract struct {
	EccoID             int32          `db:"ecco_id" json:"eccoId"`
	EccoEntityID       int32          `db:"ecco_entity_id" json:"eccoEntityId"`
	EccoContractNo     string `db:"ecco_contract_no" json:"eccoContractNo"`
	EccoContractDate   time.Time   `db:"ecco_contract_date" json:"eccoContractDate"`
	EccoStartDate      time.Time   `db:"ecco_start_date" json:"eccoStartDate"`
	EccoEndDate        time.Time   `db:"ecco_end_date" json:"eccoEndDate"`
	EccoNotes          string `db:"ecco_notes" json:"eccoNotes"`
	EccoModifiedDate   time.Time   `db:"ecco_modified_date" json:"eccoModifiedDate"`
	EccoMediaLink      string `db:"ecco_media_link" json:"eccoMediaLink"`
	EccoJotyID         int32  `db:"ecco_joty_id" json:"eccoJotyId"`
	EccoAccountManager int32  `db:"ecco_account_manager" json:"eccoAccountManager"`
	EccoClitID         int32  `db:"ecco_clit_id" json:"eccoClitId"`
	EccoStatus         string `db:"ecco_status" json:"eccoStatus"`
}

type HrEmployeeDepartmentHistory struct {
	EdhiID           int32         `db:"edhi_id" json:"edhiId"`
	EdhiEntityID     int32         `db:"edhi_entity_id" json:"edhiEntityId"`
	EdhiStartDate    time.Time  `db:"edhi_start_date" json:"edhiStartDate"`
	EdhiEndDate      time.Time  `db:"edhi_end_date" json:"edhiEndDate"`
	EdhiModifiedDate time.Time  `db:"edhi_modified_date" json:"edhiModifiedDate"`
	EdhiDeptID       int32 `db:"edhi_dept_id" json:"edhiDeptId"`
}

type HrEmployeePayHistory struct {
	EphiEntityID       int32         `db:"ephi_entity_id" json:"ephiEntityId"`
	EphiRateChangeDate time.Time     `db:"ephi_rate_change_date" json:"ephiRateChangeDate"`
	EphiRateSalary     int32 `db:"ephi_rate_salary" json:"ephiRateSalary"`
	EphiPayFrequence   int16 `db:"ephi_pay_frequence" json:"ephiPayFrequence"`
	EphiModifiedDate   time.Time  `db:"ephi_modified_date" json:"ephiModifiedDate"`
}
